sudo: required
services:
  - docker

before_install:
  - docker build -t sujeevuthayakumar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sujeevuthayakumar/react-test npm test

after_success:
  - docker build -t sujeevuthayakumar/mulit-client ./client
  - docker build -t sujeevuthayakumar/multi-nginx ./nginx
  - docker build -t sujeevuthayakumar/multi-server ./server
  - docker build -t sujeevuthayakumar/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push sujeevuthayakumar/mulit-client
  - docker push sujeevuthayakumar/multi-nginx
  - docker push sujeevuthayakumar/multi-server
  - docker push sujeevuthayakumar/multi-worker